// We import the enums generated by Prisma to ensure our types always match the database.
import { 
  AssetStatus as PrismaAssetStatus, 
  RiskLevel as PrismaRiskLevel,
  AssessmentStatus as PrismaAssessmentStatus,
  Prisma, // Import Prisma to use its JsonObject type
} from '@prisma/client';

// Re-exporting them makes it easy to use these types throughout the frontend.
export type AssetStatus = PrismaAssetStatus;
export type RiskLevel = PrismaRiskLevel;
export type AssessmentStatus = PrismaAssessmentStatus;

export const AssetStatusEnum = PrismaAssetStatus;
export const RiskLevelEnum = PrismaRiskLevel;
export const AssessmentStatusEnum = PrismaAssessmentStatus;


// The core interface for an AI Asset, matching our database model.
export interface AIAsset {
  id: string;
  name: string;
  owner: string;
  businessPurpose: string;
  status: AssetStatus;
  riskClassification: RiskLevel;
  dateRegistered: string; 
  updatedAt: string;      
}

// NEW: The interface for a single Assessment, matching our database model.
export interface Assessment {
  id: string;
  name: string;
  status: AssessmentStatus;
  questions: Prisma.JsonObject; // The questionnaire is a flexible JSON object
  createdAt: string;
  updatedAt: string;
  assetId: string;
}

