// We import the enums generated by Prisma to ensure our types always match the database.
import { 
  AssetStatus as PrismaAssetStatus, 
  RiskLevel as PrismaRiskLevel,
  AssessmentStatus as PrismaAssessmentStatus,
  Prisma,
} from '@prisma/client';

// Re-exporting them makes it easy to use these types throughout the frontend.
export type AssetStatus = PrismaAssetStatus;
export type RiskLevel = PrismaRiskLevel;
export type AssessmentStatus = PrismaAssessmentStatus;

export const AssetStatusEnum = PrismaAssetStatus;
export const RiskLevelEnum = PrismaRiskLevel;
export const AssessmentStatusEnum = PrismaAssessmentStatus;


// The core interface for an AI Asset
export interface AIAsset {
  id: string;
  name: string;
  owner: string;
  businessPurpose: string;
  status: AssetStatus;
  riskClassification: RiskLevel;
  dateRegistered: string; 
  updatedAt: string;
  vendor?: {
    name: string;
  } | null;
}

// The interface for a single Assessment
export interface Assessment {
  id: string;
  name: string;
  status: AssessmentStatus;
  questions: Prisma.JsonObject;
  createdAt: string;
  updatedAt: string;
  assetId: string;
}

// --- THIS IS THE KEY CHANGE ---
// The interface for an Audit Log entry, now including the user
export interface AuditLog {
  id: string;
  action: string;
  details: string;
  createdAt: string;
  user: { // The user object is now part of the log
    name: string | null;
    email: string | null;
  } | null;
}
// -----------------------------

